name: Deploy to AWS
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: repo:pattyt0@123456/aws-session-1@1398716925:ref:refs/heads/main
          aws-region: us-east-1
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cf-template.yaml \
            --stack-name pm-ec2-demo \
            --no-fail-on-empty-changeset